### ISSUE TITLE
Multi GPU

### ISSUE THREAD

**Issue by mehdi-shiba** [carpedm20/DiscoGAN-pytorch#4]
Thanks for the PyTorch implementation of DiscoGAN.
I am having troubles running it with multiple GPUs though.
I think the first problem is in the `config.py` file, where it casts the `num_gpu` argument to a bool instead of an int.
https://github.com/carpedm20/DiscoGAN-pytorch/blob/2feae821dcea201b5461db58e2438af97f11cb63/config.py#L53
But even fixing that, the code will only run when `--num_gpu=1` and not when `--num_gpu=2`.
Here's the traceback error:
<details>

Error:
```
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    main(config)
  File "main.py", line 33, in main
    trainer.train()
  File "/home/***/Documents/DiscoGAN-pytorch-master/trainer.py", line 187, in train
    x_AB = self.G_AB(x_A).detach()
  File "/home/***/.pyenv/versions/2.7.13/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/***/Documents/DiscoGAN-pytorch-master/models.py", line 45, in forward
    return nn.parallel.data_parallel(self.main, x, gpu_ids)
  File "/home/***/.pyenv/versions/2.7.13/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 101, in data_parallel
    replicas = replicate(module, device_ids[:len(inputs)])
  File "/home/***/.pyenv/versions/2.7.13/lib/python2.7/site-packages/torch/nn/parallel/replicate.py", line 10, in replicate
    params = list(network.parameters())
AttributeError: 'function' object has no attribute 'parameters'
```
</details>

Any idea what could be the cause?

**Comment by carpedm20** [comment]
I see. I don't have a server that has a multiple gpu so I couldn't test it but follow the tutorial of documents. I'll check it out if I can.

**Comment by mehdi-shiba** [comment]
Thanks for replying. I think I'm slowly understanding the problem here, by comparing with DCGAN tutorial from the PyTorch repository. 
When `num_gpu>1`, this following line is supposed to send each `GeneratorCNN` to the `data_parallel` function. However, it is not given a proper Pytorch `Module`, but a method (it is given `main` from `def main(self, x):`
https://github.com/carpedm20/DiscoGAN-pytorch/blob/2feae821dcea201b5461db58e2438af97f11cb63/models.py#L45
Thtat's why the `'function' object has no attribute 'parameters'` error happens, the `main` method has no parameters!
I'm trying to see if i can maybe fix it.

**Comment by mehdi-shiba** [comment]
Got it working on a machine with 2 GPUs. Thanks again for the implementation.
(I will be trying to benchmark training speed on 1 GPU vs 2 GPUs, curious to see what kind of effect it has...)

**Comment by carpedm20** [comment]
@mehdi-shiba Thanks for the PR! I definitely want to know how 2 GPUs affect the training time with pytorch. If you don't mind, could you share me the result here? Thanks!
