### ISSUE TITLE
'unexpected key "module.layer_module.0.weight" in state_dict'

### ISSUE THREAD

**Issue by shenqixiaojiang** [carpedm20/DiscoGAN-pytorch#6]
when I **test** my model, the problem 'unexpected key "module.layer_module.0.weight" in state_dict'  happened. Did you meet the problem?

**Comment by shenqixiaojiang** [comment]
The link [https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686](url) is work for me.

**Comment by chamantonio** [comment]
I also encountered this error "KeyError: 'unexpected key "module.layer_module.0.weight" in state_dict'". Have you solved the probelm? @shenqixiaojiang Thanks!
