### ISSUE TITLE
How to increase the size of image while training?

### ISSUE THREAD

**Issue by kshitizrimal** [carpedm20/DiscoGAN-pytorch#7]
It downsizes my dataset image to the height of 68px while training

**Comment by awentzonline** [comment]
`main.py` has the option `--input_scale_size` so you'd do something like `main.py --input_scale_size=128` for 128px. You may also need to change the networks a bit if you use a size other than 64px. For powers of two (I think) you can just add/remove layers in [this part of the code](https://github.com/carpedm20/DiscoGAN-pytorch/blob/master/trainer.py#L82).
